// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	entities "src/internal/entities"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// IADopingRepository is an autogenerated mock type for the IADopingRepository type
type IADopingRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ad
func (_m *IADopingRepository) Create(ad *entities.Antidoping) error {
	ret := _m.Called(ad)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Antidoping) error); ok {
		r0 = rf(ad)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetADopingBySmID provides a mock function with given fields: sportsmanID
func (_m *IADopingRepository) GetADopingBySmID(sportsmanID uuid.UUID) (*entities.Antidoping, error) {
	ret := _m.Called(sportsmanID)

	if len(ret) == 0 {
		panic("no return value specified for GetADopingBySmID")
	}

	var r0 *entities.Antidoping
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*entities.Antidoping, error)); ok {
		return rf(sportsmanID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *entities.Antidoping); ok {
		r0 = rf(sportsmanID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Antidoping)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(sportsmanID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ad
func (_m *IADopingRepository) Update(ad *entities.Antidoping) error {
	ret := _m.Called(ad)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Antidoping) error); ok {
		r0 = rf(ad)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIADopingRepository creates a new instance of IADopingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIADopingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IADopingRepository {
	mock := &IADopingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
