// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	entities "src/internal/entities"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ICoachRepository is an autogenerated mock type for the ICoachRepository type
type ICoachRepository struct {
	mock.Mock
}

// AddSportsman provides a mock function with given fields: coachID, smID
func (_m *ICoachRepository) AddSportsman(coachID uuid.UUID, smID uuid.UUID) (*entities.SportsmenCoach, error) {
	ret := _m.Called(coachID, smID)

	if len(ret) == 0 {
		panic("no return value specified for AddSportsman")
	}

	var r0 *entities.SportsmenCoach
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) (*entities.SportsmenCoach, error)); ok {
		return rf(coachID, smID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) *entities.SportsmenCoach); ok {
		r0 = rf(coachID, smID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.SportsmenCoach)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(coachID, smID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: coach
func (_m *ICoachRepository) Create(coach *entities.Coach) error {
	ret := _m.Called(coach)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Coach) error); ok {
		r0 = rf(coach)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCoachByID provides a mock function with given fields: coachID
func (_m *ICoachRepository) GetCoachByID(coachID uuid.UUID) (*entities.Coach, error) {
	ret := _m.Called(coachID)

	if len(ret) == 0 {
		panic("no return value specified for GetCoachByID")
	}

	var r0 *entities.Coach
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*entities.Coach, error)); ok {
		return rf(coachID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *entities.Coach); ok {
		r0 = rf(coachID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Coach)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(coachID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCoaches provides a mock function with given fields:
func (_m *ICoachRepository) ListCoaches() ([]*entities.Coach, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListCoaches")
	}

	var r0 []*entities.Coach
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*entities.Coach, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*entities.Coach); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Coach)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSportsmen provides a mock function with given fields: coachID
func (_m *ICoachRepository) ListSportsmen(coachID uuid.UUID) ([]*entities.Sportsman, error) {
	ret := _m.Called(coachID)

	if len(ret) == 0 {
		panic("no return value specified for ListSportsmen")
	}

	var r0 []*entities.Sportsman
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]*entities.Sportsman, error)); ok {
		return rf(coachID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []*entities.Sportsman); ok {
		r0 = rf(coachID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Sportsman)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(coachID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: coach
func (_m *ICoachRepository) Update(coach *entities.Coach) error {
	ret := _m.Called(coach)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Coach) error); ok {
		r0 = rf(coach)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewICoachRepository creates a new instance of ICoachRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICoachRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICoachRepository {
	mock := &ICoachRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
