// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	domain "src/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ISportsmanRepository is an autogenerated mock type for the ISportsmanRepository type
type ISportsmanRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: sportsman
func (_m *ISportsmanRepository) Create(sportsman *domain.Sportsman) error {
	ret := _m.Called(sportsman)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Sportsman) error); ok {
		r0 = rf(sportsman)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: sportsmanID
func (_m *ISportsmanRepository) Delete(sportsmanID uuid.UUID) error {
	ret := _m.Called(sportsmanID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(sportsmanID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSportsmanByID provides a mock function with given fields: sportsmanID
func (_m *ISportsmanRepository) GetSportsmanByID(sportsmanID uuid.UUID) (*domain.Sportsman, error) {
	ret := _m.Called(sportsmanID)

	if len(ret) == 0 {
		panic("no return value specified for GetSportsmanByID")
	}

	var r0 *domain.Sportsman
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*domain.Sportsman, error)); ok {
		return rf(sportsmanID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *domain.Sportsman); ok {
		r0 = rf(sportsmanID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Sportsman)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(sportsmanID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListResults provides a mock function with given fields: sportsmanID
func (_m *ISportsmanRepository) ListResults(sportsmanID uuid.UUID) ([]*domain.Result, error) {
	ret := _m.Called(sportsmanID)

	if len(ret) == 0 {
		panic("no return value specified for ListResults")
	}

	var r0 []*domain.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]*domain.Result, error)); ok {
		return rf(sportsmanID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []*domain.Result); ok {
		r0 = rf(sportsmanID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(sportsmanID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSportsmen provides a mock function with given fields: page, batch, sort, filter
func (_m *ISportsmanRepository) ListSportsmen(page int, batch int, sort string, filter string) ([]*domain.Sportsman, error) {
	ret := _m.Called(page, batch, sort, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListSportsmen")
	}

	var r0 []*domain.Sportsman
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, string, string) ([]*domain.Sportsman, error)); ok {
		return rf(page, batch, sort, filter)
	}
	if rf, ok := ret.Get(0).(func(int, int, string, string) []*domain.Sportsman); ok {
		r0 = rf(page, batch, sort, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Sportsman)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string, string) error); ok {
		r1 = rf(page, batch, sort, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: sportsman
func (_m *ISportsmanRepository) Update(sportsman *domain.Sportsman) (*domain.Sportsman, error) {
	ret := _m.Called(sportsman)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Sportsman
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.Sportsman) (*domain.Sportsman, error)); ok {
		return rf(sportsman)
	}
	if rf, ok := ret.Get(0).(func(*domain.Sportsman) *domain.Sportsman); ok {
		r0 = rf(sportsman)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Sportsman)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.Sportsman) error); ok {
		r1 = rf(sportsman)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewISportsmanRepository creates a new instance of ISportsmanRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISportsmanRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISportsmanRepository {
	mock := &ISportsmanRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
